repos:
  - repo: https://github.com/gherynos/pre-commit-java
    rev: v0.2.1
    hooks:
      - id: checkstyle
        exclude: /test/
        args: ["-c", "sun_checks.xml"]
  - repo: https://github.com/thoughtworks/talisman
    rev: v1.31.0
    hooks:
      - id: talisman-commit
        entry: talisman --githook pre-commit -p **/*.java